name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Create deployment package
      run: |
        # Zip all files excluding .git to avoid pushing version history
        zip -r deploy.zip . -x "*.git*"

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: insurance-prediction-app
        environment_name: insurance-prediction-env
        version_label: "insurance-app-${{ github.sha }}"
        region: eu-north-1
        deployment_package: deploy.zip
